server:
  port: 8083
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
## Info endpoint
info:
  app:
    name: Orders management service
    description: Orders  Management Microservice
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    
oauth2:
  resource:
    jwt:
      keyUri: http://localhost:9999/uaa/oauth/token_key
    id: openid
    serviceId: ${PREFIX:}resource
  client:
    tokenUri: http://localhost:9999/uaa/oauth/token
    authorizationUri: http://localhost:9999/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret    
    
---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: MYSQL
eureka:
  instance:
    hostname: ms-catalog-service.cf.deepsouthcloud.com
    nonSecurePort: 80